services:
  - type: web
    name: trustichain-backend
    runtime: node
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NODE_ENV
        value: production
